import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"


[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 5
y = 5


[font]
size = 16.0
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }

